# This will be the first part of the title tag for your site <title> site.name + page.title </title>
name: "Microbeats"
# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
descripiton: "Beats Created in Under an Hour"

# Owner (organization or individual) of site content
author: "Jxnblk"

#url: "[http:// ]"
url: "http://localhost:4000"

# Pagination variable for how many posts to show in a list
paginate: 8

# Style of permalinks
permalink: /:title/

# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
#permalink: /blog/:yearr/:month/:day/:title       => /blog/2009/04/29/slap-chop/index.html

# If you want to display social nav - fill out the appropriate handles. Delete or comment out unneeded networks. 
github: "jxnblk"
twitter: "jxnblk"
dribbble: "jxnblk"
soundcloud: "jxnblk"

# UnComment once you have pygments installed. Used for code syntax highlighting.
pygments: true
